// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVcDataPointLabel;
class CVcBrush;
class CVcPen;
class CVcMarker;

/////////////////////////////////////////////////////////////////////////////
// CVcDataPoint wrapper class

class CVcDataPoint : public COleDispatchDriver
{
public:
	CVcDataPoint() {}		// Calls COleDispatchDriver default constructor
	CVcDataPoint(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVcDataPoint(const CVcDataPoint& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CVcDataPointLabel GetDataPointLabel();
	CVcBrush GetBrush();
	CVcPen GetEdgePen();
	CVcMarker GetMarker();
	float GetOffset();
	void SetOffset(float newValue);
	void ResetCustom();
	void Select();
};
