// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vcaxisgrid.h"


/////////////////////////////////////////////////////////////////////////////
// CVcAxisGrid properties

/////////////////////////////////////////////////////////////////////////////
// CVcAxisGrid operations

LPDISPATCH CVcAxisGrid::GetMinorPen()
{
	LPDISPATCH result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&result, NULL);
	return result;
}

LPDISPATCH CVcAxisGrid::GetMajorPen()
{
	LPDISPATCH result;
	InvokeHelper(0x2, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&result, NULL);
	return result;
}
