// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVcIntersection wrapper class

class CVcIntersection : public COleDispatchDriver
{
public:
	CVcIntersection() {}		// Calls COleDispatchDriver default constructor
	CVcIntersection(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVcIntersection(const CVcIntersection& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetAuto();
	void SetAuto(BOOL bNewValue);
	double GetPoint();
	void SetPoint(double newValue);
	long GetAxisID();
	short GetIndex();
	BOOL GetLabelsInsidePlot();
	void SetLabelsInsidePlot(BOOL bNewValue);
};
