// Color.h

#ifndef _COLOR
#define _COLOR

#define BLACK				RGB(  0,  0,  0)
#define BLUE				RGB(  0,  0,255)
#define GREEN				RGB(  0,255,  0)
#define CYAN				RGB(  0,255,255)
#define RED					RGB(255,  0,  0)
#define MAGENTA				RGB(255,  0,255)
#define YELLOW				RGB(255,255,  0)
#define WHITE				RGB(255,255,255)
#define DARK_BLUE			RGB(  0,  0,128)
#define DARK_GREEN			RGB(  0,128,  0)
#define DARK_CYAN			RGB(  0,128,128)
#define DARK_RED			RGB(128,  0,  0)
#define DARK_MAGENTA		RGB(128,  0,128)
#define DARK_YELLOW			RGB(128,128,  0)
#define DARK_GRAY			RGB(128,128,128)
#define LIGHT_BLUE			RGB(  0,  0,192)
#define LIGHT_GREEN			RGB(  0,192,  0)
#define LIGHT_CYAN			RGB(  0,192,192)
#define LIGHT_RED			RGB(192,  0,  0)
#define LIGHT_MAGENTA		RGB(192,  0,192)
#define LIGHT_YELLOW		RGB(192,192,  0)
#define PALE_GRAY			RGB(220,220,220)
#define LIGHT_GRAY			RGB(192,192,192)

#define DEF_RACK_COLOR	RGB(128,192,192)
//#define DEF_RACK_COLOR	RGB(150,187,187)

#endif // _COLOR
