// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVcSeriesPosition wrapper class

class CVcSeriesPosition : public COleDispatchDriver
{
public:
	CVcSeriesPosition() {}		// Calls COleDispatchDriver default constructor
	CVcSeriesPosition(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVcSeriesPosition(const CVcSeriesPosition& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetExcluded();
	void SetExcluded(BOOL bNewValue);
	BOOL GetHidden();
	void SetHidden(BOOL bNewValue);
	short GetOrder();
	void SetOrder(short nNewValue);
	short GetStackOrder();
	void SetStackOrder(short nNewValue);
};
