#if !defined(AFX_VCAXISTITLE_H__8AFBD38F_8C1F_11D2_94DF_080009A4CC9D__INCLUDED_)
#define AFX_VCAXISTITLE_H__8AFBD38F_8C1F_11D2_94DF_080009A4CC9D__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVcFont;

/////////////////////////////////////////////////////////////////////////////
// CVcAxisTitle wrapper class

class CVcAxisTitle : public COleDispatchDriver
{
public:
	CVcAxisTitle() {}		// Calls COleDispatchDriver default constructor
	CVcAxisTitle(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVcAxisTitle(const CVcAxisTitle& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	LPDISPATCH GetBackdrop();
	CVcFont GetVtFont();
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	LPDISPATCH GetTextLayout();
	short GetTextLength();
	void SetRefFont(LPDISPATCH newValue);
	LPDISPATCH GetFont();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCAXISTITLE_H__8AFBD38F_8C1F_11D2_94DF_080009A4CC9D__INCLUDED_)
