// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVcPen;

/////////////////////////////////////////////////////////////////////////////
// CVcAxisGrid wrapper class

class CVcAxisGrid : public COleDispatchDriver
{
public:
	CVcAxisGrid() {}		// Calls COleDispatchDriver default constructor
	CVcAxisGrid(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVcAxisGrid(const CVcAxisGrid& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CVcPen GetMinorPen();
	CVcPen GetMajorPen();
};
