#if !defined(AFX_VCPLOTBASE_H__8AFBD386_8C1F_11D2_94DF_080009A4CC9D__INCLUDED_)
#define AFX_VCPLOTBASE_H__8AFBD386_8C1F_11D2_94DF_080009A4CC9D__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVcPlotBase wrapper class

class CVcPlotBase : public COleDispatchDriver
{
public:
	CVcPlotBase() {}		// Calls COleDispatchDriver default constructor
	CVcPlotBase(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVcPlotBase(const CVcPlotBase& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	float GetBaseHeight();
	void SetBaseHeight(float newValue);
	LPDISPATCH GetBrush();
	LPDISPATCH GetPen();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCPLOTBASE_H__8AFBD386_8C1F_11D2_94DF_080009A4CC9D__INCLUDED_)
