#if !defined(AFX_VCDATAPOINT_H__8AFBD382_8C1F_11D2_94DF_080009A4CC9D__INCLUDED_)
#define AFX_VCDATAPOINT_H__8AFBD382_8C1F_11D2_94DF_080009A4CC9D__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVcMarker;

/////////////////////////////////////////////////////////////////////////////
// CVcDataPoint wrapper class

class CVcDataPoint : public COleDispatchDriver
{
public:
	CVcDataPoint() {}		// Calls COleDispatchDriver default constructor
	CVcDataPoint(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVcDataPoint(const CVcDataPoint& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	LPDISPATCH GetDataPointLabel();
	LPDISPATCH GetBrush();
	LPDISPATCH GetEdgePen();
	CVcMarker GetMarker();
	float GetOffset();
	void SetOffset(float newValue);
	void ResetCustom();
	void Select();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCDATAPOINT_H__8AFBD382_8C1F_11D2_94DF_080009A4CC9D__INCLUDED_)
